platforms:
- name: "micro"
  domain: "micro.mu"
  gslb: "cloudflare"
  kv: "cloudflare"
  regions:
  - provider: do
    region: lon1
    control:
    - api
    - bot
    resource:
    - cockroachdb
    network:
    - registry
    - web
    - store
  - provider: azure
    region: uksouth
    control: []
    resource: []
    network: []
- name: "somewhere"
  domain: "nowhere.com"
  gslb: "cloudflare"
  kv: "cloudflare"
  regions:
  - provider: azure
    region: uksouth
    control: []
    resource: []
    network: []
