apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-registry
  labels:
    micro: runtime
    name: micro-registry
  annotations:
    name: "go.micro.registry"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-registry
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-registry
        micro: runtime
    spec:
      containers:
      - name: registry
        env:
        - name: MICRO_AUTH
          value: "jwt"
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-keypair
              key: public
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-keypair
              key: private
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        args:
        - registry
        image: micro/micro
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: registry-port
