apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-runtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-runtime
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/logs
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: micro-runtime
subjects:
- kind: ServiceAccount
  name: micro-runtime
  namespace: default
roleRef:
  kind: ClusterRole
  name: micro-runtime
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-runtime
subjects:
- kind: ServiceAccount
  name: micro-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-runtime
  labels:
    micro: runtime
    name: micro-runtime
  annotations:
    name: "go.micro.runtime"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-runtime
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-runtime
        micro: runtime
    spec:
      serviceAccount: micro-runtime
      serviceAccountName: micro-runtime
      containers:
      - name: runtime
        env:
        - name: MICRO_AUTH
          value: "jwt"
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-keypair
              key: public
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-keypair
              key: private
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_RUNTIME
          value: "kubernetes"
        - name: MICRO_RUNTIME_PROFILE
          value: "platform"
        - name: MICRO_AUTO_UPDATE
          value: "true"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        - name: MICRO_STORE
          value: "cockroach"
        - name: MICRO_STORE_ADDRESS
          value: "postgres://root@cockroachdb-public:26257/?sslmode=disable"
        args:
        - runtime
        image: micro/micro
        imagePullPolicy: Always
