// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sims.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Hub service

func NewHubEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Hub service

type HubService interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...client.CallOption) (*ConnectResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...client.CallOption) (*HeartbeatResponse, error)
	Events(ctx context.Context, in *EventsRequest, opts ...client.CallOption) (Hub_EventsService, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...client.CallOption) (*DisconnectResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type hubService struct {
	c    client.Client
	name string
}

func NewHubService(name string, c client.Client) HubService {
	return &hubService{
		c:    c,
		name: name,
	}
}

func (c *hubService) Connect(ctx context.Context, in *ConnectRequest, opts ...client.CallOption) (*ConnectResponse, error) {
	req := c.c.NewRequest(c.name, "Hub.Connect", in)
	out := new(ConnectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubService) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...client.CallOption) (*HeartbeatResponse, error) {
	req := c.c.NewRequest(c.name, "Hub.Heartbeat", in)
	out := new(HeartbeatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubService) Events(ctx context.Context, in *EventsRequest, opts ...client.CallOption) (Hub_EventsService, error) {
	req := c.c.NewRequest(c.name, "Hub.Events", &EventsRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &hubServiceEvents{stream}, nil
}

type Hub_EventsService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*Event, error)
}

type hubServiceEvents struct {
	stream client.Stream
}

func (x *hubServiceEvents) Close() error {
	return x.stream.Close()
}

func (x *hubServiceEvents) Context() context.Context {
	return x.stream.Context()
}

func (x *hubServiceEvents) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hubServiceEvents) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hubServiceEvents) Recv() (*Event, error) {
	m := new(Event)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hubService) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...client.CallOption) (*DisconnectResponse, error) {
	req := c.c.NewRequest(c.name, "Hub.Disconnect", in)
	out := new(DisconnectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "Hub.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hub service

type HubHandler interface {
	Connect(context.Context, *ConnectRequest, *ConnectResponse) error
	Heartbeat(context.Context, *HeartbeatRequest, *HeartbeatResponse) error
	Events(context.Context, *EventsRequest, Hub_EventsStream) error
	Disconnect(context.Context, *DisconnectRequest, *DisconnectResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterHubHandler(s server.Server, hdlr HubHandler, opts ...server.HandlerOption) error {
	type hub interface {
		Connect(ctx context.Context, in *ConnectRequest, out *ConnectResponse) error
		Heartbeat(ctx context.Context, in *HeartbeatRequest, out *HeartbeatResponse) error
		Events(ctx context.Context, stream server.Stream) error
		Disconnect(ctx context.Context, in *DisconnectRequest, out *DisconnectResponse) error
		List(ctx context.Context, in *ListRequest, out *ListResponse) error
	}
	type Hub struct {
		hub
	}
	h := &hubHandler{hdlr}
	return s.Handle(s.NewHandler(&Hub{h}, opts...))
}

type hubHandler struct {
	HubHandler
}

func (h *hubHandler) Connect(ctx context.Context, in *ConnectRequest, out *ConnectResponse) error {
	return h.HubHandler.Connect(ctx, in, out)
}

func (h *hubHandler) Heartbeat(ctx context.Context, in *HeartbeatRequest, out *HeartbeatResponse) error {
	return h.HubHandler.Heartbeat(ctx, in, out)
}

func (h *hubHandler) Events(ctx context.Context, stream server.Stream) error {
	m := new(EventsRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.HubHandler.Events(ctx, m, &hubEventsStream{stream})
}

type Hub_EventsStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Event) error
}

type hubEventsStream struct {
	stream server.Stream
}

func (x *hubEventsStream) Close() error {
	return x.stream.Close()
}

func (x *hubEventsStream) Context() context.Context {
	return x.stream.Context()
}

func (x *hubEventsStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *hubEventsStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *hubEventsStream) Send(m *Event) error {
	return x.stream.Send(m)
}

func (h *hubHandler) Disconnect(ctx context.Context, in *DisconnectRequest, out *DisconnectResponse) error {
	return h.HubHandler.Disconnect(ctx, in, out)
}

func (h *hubHandler) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.HubHandler.List(ctx, in, out)
}

// Api Endpoints for Publisher service

func NewPublisherEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Publisher service

type PublisherService interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...client.CallOption) (*PublishResponse, error)
}

type publisherService struct {
	c    client.Client
	name string
}

func NewPublisherService(name string, c client.Client) PublisherService {
	return &publisherService{
		c:    c,
		name: name,
	}
}

func (c *publisherService) Publish(ctx context.Context, in *PublishRequest, opts ...client.CallOption) (*PublishResponse, error) {
	req := c.c.NewRequest(c.name, "Publisher.Publish", in)
	out := new(PublishResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Publisher service

type PublisherHandler interface {
	Publish(context.Context, *PublishRequest, *PublishResponse) error
}

func RegisterPublisherHandler(s server.Server, hdlr PublisherHandler, opts ...server.HandlerOption) error {
	type publisher interface {
		Publish(ctx context.Context, in *PublishRequest, out *PublishResponse) error
	}
	type Publisher struct {
		publisher
	}
	h := &publisherHandler{hdlr}
	return s.Handle(s.NewHandler(&Publisher{h}, opts...))
}

type publisherHandler struct {
	PublisherHandler
}

func (h *publisherHandler) Publish(ctx context.Context, in *PublishRequest, out *PublishResponse) error {
	return h.PublisherHandler.Publish(ctx, in, out)
}

// Api Endpoints for Subscriber service

func NewSubscriberEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Subscriber service

type SubscriberService interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...client.CallOption) (*SubscribeResponse, error)
}

type subscriberService struct {
	c    client.Client
	name string
}

func NewSubscriberService(name string, c client.Client) SubscriberService {
	return &subscriberService{
		c:    c,
		name: name,
	}
}

func (c *subscriberService) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...client.CallOption) (*SubscribeResponse, error) {
	req := c.c.NewRequest(c.name, "Subscriber.Subscribe", in)
	out := new(SubscribeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Subscriber service

type SubscriberHandler interface {
	Subscribe(context.Context, *SubscribeRequest, *SubscribeResponse) error
}

func RegisterSubscriberHandler(s server.Server, hdlr SubscriberHandler, opts ...server.HandlerOption) error {
	type subscriber interface {
		Subscribe(ctx context.Context, in *SubscribeRequest, out *SubscribeResponse) error
	}
	type Subscriber struct {
		subscriber
	}
	h := &subscriberHandler{hdlr}
	return s.Handle(s.NewHandler(&Subscriber{h}, opts...))
}

type subscriberHandler struct {
	SubscriberHandler
}

func (h *subscriberHandler) Subscribe(ctx context.Context, in *SubscribeRequest, out *SubscribeResponse) error {
	return h.SubscriberHandler.Subscribe(ctx, in, out)
}
