// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sims.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_ERR_UNSPECIFIED    ErrorCode = 0
	ErrorCode_ERR_NOT_FOUND      ErrorCode = 1
	ErrorCode_ERR_ALREADY_EXISTS ErrorCode = 2
	ErrorCode_ERR_MISSING_USERID ErrorCode = 3
	ErrorCode_ERR_MISSING_HEADER ErrorCode = 4
	ErrorCode_ERR_NO_CONSUMER    ErrorCode = 5
)

var ErrorCode_name = map[int32]string{
	0: "ERR_UNSPECIFIED",
	1: "ERR_NOT_FOUND",
	2: "ERR_ALREADY_EXISTS",
	3: "ERR_MISSING_USERID",
	4: "ERR_MISSING_HEADER",
	5: "ERR_NO_CONSUMER",
}

var ErrorCode_value = map[string]int32{
	"ERR_UNSPECIFIED":    0,
	"ERR_NOT_FOUND":      1,
	"ERR_ALREADY_EXISTS": 2,
	"ERR_MISSING_USERID": 3,
	"ERR_MISSING_HEADER": 4,
	"ERR_NO_CONSUMER":    5,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{0}
}

type EventType int32

const (
	EventType_EVT_HEARTBEAT EventType = 0
	EventType_EVT_TEXT      EventType = 1
	EventType_EVT_JSON      EventType = 2
	EventType_EVT_PROTOBUF  EventType = 3
	EventType_EVT_BINARY    EventType = 4
)

var EventType_name = map[int32]string{
	0: "EVT_HEARTBEAT",
	1: "EVT_TEXT",
	2: "EVT_JSON",
	3: "EVT_PROTOBUF",
	4: "EVT_BINARY",
}

var EventType_value = map[string]int32{
	"EVT_HEARTBEAT": 0,
	"EVT_TEXT":      1,
	"EVT_JSON":      2,
	"EVT_PROTOBUF":  3,
	"EVT_BINARY":    4,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{1}
}

type ServerConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{0}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

type User struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

type Header struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Groups               []string `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Header) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Header) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Header) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Event struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=sims.proto.EventType" json:"type,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EVT_HEARTBEAT
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EventStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStreamRequest) Reset()         { *m = EventStreamRequest{} }
func (m *EventStreamRequest) String() string { return proto.CompactTextString(m) }
func (*EventStreamRequest) ProtoMessage()    {}
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{4}
}

func (m *EventStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStreamRequest.Unmarshal(m, b)
}
func (m *EventStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStreamRequest.Marshal(b, m, deterministic)
}
func (m *EventStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStreamRequest.Merge(m, src)
}
func (m *EventStreamRequest) XXX_Size() int {
	return xxx_messageInfo_EventStreamRequest.Size(m)
}
func (m *EventStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventStreamRequest proto.InternalMessageInfo

type RegisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{5}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{6}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type UnregisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterRequest) Reset()         { *m = UnregisterRequest{} }
func (m *UnregisterRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterRequest) ProtoMessage()    {}
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{7}
}

func (m *UnregisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterRequest.Unmarshal(m, b)
}
func (m *UnregisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterRequest.Merge(m, src)
}
func (m *UnregisterRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterRequest.Size(m)
}
func (m *UnregisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterRequest proto.InternalMessageInfo

type UnregisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterResponse) Reset()         { *m = UnregisterResponse{} }
func (m *UnregisterResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterResponse) ProtoMessage()    {}
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{8}
}

func (m *UnregisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterResponse.Unmarshal(m, b)
}
func (m *UnregisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterResponse.Merge(m, src)
}
func (m *UnregisterResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterResponse.Size(m)
}
func (m *UnregisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterResponse proto.InternalMessageInfo

type PublishRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{9}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{10}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{11}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{12}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type HeartbeatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{13}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{14}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{15}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type Channel struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Birth                string   `protobuf:"bytes,3,opt,name=birth,proto3" json:"birth,omitempty"`
	LastHeartbeat        string   `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{16}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Channel) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Channel) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

func (m *Channel) GetLastHeartbeat() string {
	if m != nil {
		return m.LastHeartbeat
	}
	return ""
}

type ListResponse struct {
	Channels             []*Channel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{17}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func init() {
	proto.RegisterEnum("sims.proto.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("sims.proto.EventType", EventType_name, EventType_value)
	proto.RegisterType((*ServerConfig)(nil), "sims.proto.ServerConfig")
	proto.RegisterType((*User)(nil), "sims.proto.User")
	proto.RegisterType((*Header)(nil), "sims.proto.Header")
	proto.RegisterType((*Event)(nil), "sims.proto.Event")
	proto.RegisterType((*EventStreamRequest)(nil), "sims.proto.EventStreamRequest")
	proto.RegisterType((*RegisterRequest)(nil), "sims.proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "sims.proto.RegisterResponse")
	proto.RegisterType((*UnregisterRequest)(nil), "sims.proto.UnregisterRequest")
	proto.RegisterType((*UnregisterResponse)(nil), "sims.proto.UnregisterResponse")
	proto.RegisterType((*PublishRequest)(nil), "sims.proto.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "sims.proto.PublishResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "sims.proto.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "sims.proto.SubscribeResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "sims.proto.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "sims.proto.HeartbeatResponse")
	proto.RegisterType((*ListRequest)(nil), "sims.proto.ListRequest")
	proto.RegisterType((*Channel)(nil), "sims.proto.Channel")
	proto.RegisterType((*ListResponse)(nil), "sims.proto.ListResponse")
}

func init() { proto.RegisterFile("sims.proto", fileDescriptor_baee4f6301954b8c) }

var fileDescriptor_baee4f6301954b8c = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdb, 0x6e, 0xe2, 0x48,
	0x10, 0x8d, 0xc1, 0x21, 0x50, 0x21, 0xc4, 0x14, 0xd9, 0x04, 0x91, 0x8b, 0x22, 0x4b, 0x2b, 0x25,
	0x79, 0x80, 0x15, 0xfb, 0xb4, 0x4f, 0x2b, 0x2e, 0x66, 0xf1, 0x6e, 0x62, 0x47, 0x6d, 0x13, 0x25,
	0xab, 0x91, 0x90, 0xc1, 0x3d, 0x60, 0x89, 0x60, 0xa6, 0xdb, 0x44, 0x8a, 0x34, 0x1f, 0x31, 0x3f,
	0x39, 0xff, 0x31, 0x6a, 0xdb, 0x18, 0x03, 0xc9, 0x13, 0xae, 0x73, 0x4e, 0x75, 0x15, 0x55, 0x75,
	0x00, 0xb8, 0xf7, 0xca, 0xeb, 0x0b, 0xe6, 0x07, 0x3e, 0xa6, 0xbe, 0xd5, 0x12, 0x14, 0x2d, 0xca,
	0xde, 0x28, 0xeb, 0xf8, 0xf3, 0xaf, 0xde, 0x44, 0xcd, 0x81, 0x3c, 0xe0, 0x94, 0xa9, 0x4b, 0xc8,
	0xf5, 0xa9, 0xe3, 0x52, 0x86, 0x97, 0x00, 0x8c, 0x7e, 0x5b, 0x52, 0x1e, 0x0c, 0x3d, 0xb7, 0x2a,
	0x5d, 0x4b, 0x37, 0x05, 0x52, 0x88, 0x11, 0xdd, 0xc5, 0x33, 0x38, 0x58, 0x72, 0xca, 0x04, 0x97,
	0x09, 0xb9, 0x9c, 0x08, 0x75, 0x17, 0xcf, 0xa1, 0xe0, 0xd2, 0x37, 0x6f, 0x4c, 0x05, 0x95, 0x0d,
	0xa9, 0x7c, 0x04, 0xe8, 0x2e, 0x9e, 0x42, 0x6e, 0xc2, 0xfc, 0xe5, 0x82, 0x57, 0xe5, 0xeb, 0xac,
	0x48, 0x8a, 0x22, 0xb5, 0x07, 0xfb, 0xda, 0x1b, 0x9d, 0x07, 0x78, 0x0b, 0x72, 0xf0, 0xbe, 0xa0,
	0x61, 0xbd, 0x52, 0xf3, 0xb7, 0xfa, 0xba, 0xe5, 0x7a, 0x28, 0xb0, 0xdf, 0x17, 0x94, 0x84, 0x12,
	0x44, 0x90, 0x5d, 0x27, 0x70, 0xc2, 0xf2, 0x45, 0x12, 0x7e, 0xab, 0x27, 0x80, 0xa1, 0xcc, 0x0a,
	0x18, 0x75, 0x5e, 0x49, 0xd4, 0xad, 0x5a, 0x86, 0x63, 0x42, 0x27, 0x1e, 0x0f, 0x28, 0x5b, 0x41,
	0x08, 0xca, 0x1a, 0xe2, 0x0b, 0x7f, 0xce, 0xa9, 0x5a, 0x81, 0xf2, 0x60, 0xce, 0xb6, 0x84, 0x27,
	0x80, 0x69, 0x30, 0x96, 0xde, 0x42, 0xe9, 0x71, 0x39, 0x9a, 0x79, 0x7c, 0x1a, 0xeb, 0xd2, 0xf3,
	0x90, 0xd2, 0xf3, 0x10, 0xc5, 0x13, 0x69, 0x9c, 0x8d, 0xa0, 0x58, 0xcb, 0x11, 0x1f, 0x33, 0x6f,
	0x44, 0x57, 0x75, 0x2a, 0x50, 0x4e, 0x61, 0x6b, 0x61, 0x9f, 0x3a, 0x2c, 0x18, 0x51, 0x27, 0x48,
	0x09, 0x53, 0x58, 0x2c, 0x3c, 0x82, 0xc3, 0x7b, 0x8f, 0x27, 0x9a, 0xef, 0x70, 0xd0, 0x99, 0x3a,
	0xf3, 0x39, 0x9d, 0x7d, 0xda, 0xd7, 0xe6, 0x9e, 0x32, 0x5b, 0x7b, 0x3a, 0x81, 0xfd, 0x91, 0xc7,
	0x82, 0x69, 0xbc, 0xc0, 0x28, 0xc0, 0xdf, 0xa1, 0x34, 0x73, 0x78, 0x30, 0x9c, 0xae, 0xea, 0x57,
	0xe5, 0x90, 0x3e, 0x12, 0x68, 0xd2, 0x94, 0xfa, 0x37, 0x14, 0xa3, 0x66, 0xa2, 0xe6, 0xb0, 0x01,
	0xf9, 0x71, 0xd4, 0x0d, 0xaf, 0x4a, 0xd7, 0xd9, 0x9b, 0xc3, 0x66, 0x25, 0xbd, 0xd7, 0xb8, 0x53,
	0x92, 0x88, 0xee, 0x7e, 0x48, 0x50, 0xd0, 0x18, 0xf3, 0x59, 0xc7, 0x77, 0x29, 0x56, 0xe0, 0x58,
	0x23, 0x64, 0x38, 0x30, 0xac, 0x47, 0xad, 0xa3, 0xf7, 0x74, 0xad, 0xab, 0xec, 0x61, 0x19, 0x8e,
	0x04, 0x68, 0x98, 0xf6, 0xb0, 0x67, 0x0e, 0x8c, 0xae, 0x22, 0xe1, 0x29, 0xa0, 0x80, 0x5a, 0xf7,
	0x44, 0x6b, 0x75, 0x5f, 0x86, 0xda, 0xb3, 0x6e, 0xd9, 0x96, 0x92, 0x59, 0xe1, 0x0f, 0xba, 0x65,
	0xe9, 0xc6, 0x3f, 0xc3, 0x81, 0xa5, 0x11, 0xbd, 0xab, 0x64, 0xb7, 0xf1, 0xbe, 0xd6, 0xea, 0x6a,
	0x44, 0x91, 0x57, 0xf5, 0x0c, 0x73, 0xd8, 0x31, 0x0d, 0x6b, 0xf0, 0xa0, 0x11, 0x65, 0xff, 0xee,
	0x0b, 0x14, 0x92, 0xfb, 0x0b, 0x8b, 0x3f, 0xd9, 0x22, 0x83, 0xd8, 0x6d, 0xad, 0x65, 0x2b, 0x7b,
	0x58, 0x84, 0xbc, 0x80, 0x6c, 0xed, 0xd9, 0x56, 0xa4, 0x55, 0xf4, 0xaf, 0x65, 0x1a, 0x4a, 0x06,
	0x15, 0x28, 0x8a, 0xe8, 0x91, 0x98, 0xb6, 0xd9, 0x1e, 0xf4, 0x94, 0x2c, 0x96, 0x00, 0x04, 0xd2,
	0xd6, 0x8d, 0x16, 0x79, 0x51, 0xe4, 0xe6, 0xcf, 0x0c, 0xe4, 0xf4, 0x07, 0x43, 0xfc, 0x5b, 0x0d,
	0xf2, 0xab, 0xc3, 0xc4, 0xf3, 0xf4, 0x98, 0xb6, 0x2e, 0xb8, 0x76, 0xf1, 0x31, 0x19, 0xcf, 0xbc,
	0x0f, 0x85, 0x64, 0x21, 0xb8, 0x21, 0xdd, 0x3e, 0xa8, 0xda, 0xe5, 0x27, 0x6c, 0xfc, 0x52, 0x1b,
	0x0e, 0x53, 0x96, 0xc2, 0xab, 0x1d, 0x4b, 0x6e, 0x78, 0xad, 0x56, 0xde, 0xe1, 0xff, 0x90, 0xf0,
	0x3f, 0x80, 0xb5, 0x89, 0x70, 0xa3, 0xe0, 0x8e, 0xe3, 0x6a, 0x57, 0x9f, 0xd1, 0x71, 0x43, 0x7f,
	0x81, 0x2c, 0xce, 0x0b, 0xcf, 0xd2, 0xba, 0xd4, 0xf5, 0xd7, 0xaa, 0xbb, 0x44, 0x94, 0xda, 0x34,
	0xa1, 0x10, 0x7b, 0x91, 0x32, 0x6c, 0xc3, 0x41, 0x1c, 0x60, 0x2d, 0x9d, 0xb1, 0x69, 0xec, 0xda,
	0xf9, 0x87, 0x5c, 0xfc, 0xe0, 0x13, 0x40, 0xe2, 0x5a, 0x26, 0x86, 0x9e, 0x44, 0x9b, 0x43, 0xdf,
	0xb6, 0xfb, 0xe6, 0xd0, 0x77, 0x8c, 0xdf, 0xbe, 0xfa, 0xff, 0x62, 0xe2, 0x05, 0xd3, 0xe5, 0xa8,
	0x3e, 0xf6, 0x5f, 0x1b, 0xce, 0x78, 0xe6, 0xf1, 0x45, 0x43, 0x64, 0x34, 0xc2, 0x8c, 0x51, 0x2e,
	0xfc, 0xf9, 0xf3, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xc9, 0xf2, 0x9a, 0xdf, 0x05, 0x00,
	0x00,
}
