// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sims.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_ERR_UNSPECIFIED        ErrorCode = 0
	ErrorCode_ERR_NOT_FOUND          ErrorCode = 1
	ErrorCode_ERR_ALREADY_EXISTS     ErrorCode = 2
	ErrorCode_ERR_MISSING_USERID     ErrorCode = 3
	ErrorCode_ERR_MISSING_HEADER     ErrorCode = 4
	ErrorCode_ERR_NO_CONSUMER        ErrorCode = 5
	ErrorCode_ERR_MISSING_EVENT      ErrorCode = 6
	ErrorCode_ERR_INVALID_EVENT_TYPE ErrorCode = 7
)

var ErrorCode_name = map[int32]string{
	0: "ERR_UNSPECIFIED",
	1: "ERR_NOT_FOUND",
	2: "ERR_ALREADY_EXISTS",
	3: "ERR_MISSING_USERID",
	4: "ERR_MISSING_HEADER",
	5: "ERR_NO_CONSUMER",
	6: "ERR_MISSING_EVENT",
	7: "ERR_INVALID_EVENT_TYPE",
}

var ErrorCode_value = map[string]int32{
	"ERR_UNSPECIFIED":        0,
	"ERR_NOT_FOUND":          1,
	"ERR_ALREADY_EXISTS":     2,
	"ERR_MISSING_USERID":     3,
	"ERR_MISSING_HEADER":     4,
	"ERR_NO_CONSUMER":        5,
	"ERR_MISSING_EVENT":      6,
	"ERR_INVALID_EVENT_TYPE": 7,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{0}
}

type EventType int32

const (
	EventType_EVT_HEARTBEAT EventType = 0
	EventType_EVT_TEXT      EventType = 1
	EventType_EVT_JSON      EventType = 2
	EventType_EVT_PROTOBUF  EventType = 3
	EventType_EVT_BINARY    EventType = 4
)

var EventType_name = map[int32]string{
	0: "EVT_HEARTBEAT",
	1: "EVT_TEXT",
	2: "EVT_JSON",
	3: "EVT_PROTOBUF",
	4: "EVT_BINARY",
}

var EventType_value = map[string]int32{
	"EVT_HEARTBEAT": 0,
	"EVT_TEXT":      1,
	"EVT_JSON":      2,
	"EVT_PROTOBUF":  3,
	"EVT_BINARY":    4,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{1}
}

type ServerConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{0}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

type User struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

type Header struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Groups               []string `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Header) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Header) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Header) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Event struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=sims.proto.EventType" json:"type,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EVT_HEARTBEAT
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EventsRequest struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{4}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type ConnectRequest struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{5}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type ConnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{6}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

type DisconnectRequest struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{7}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type DisconnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{8}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

type PublishRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{9}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PublishRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type PublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{10}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{11}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{12}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type HeartbeatRequest struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{13}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{14}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{15}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type Channel struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Birth                string   `protobuf:"bytes,3,opt,name=birth,proto3" json:"birth,omitempty"`
	LastHeartbeat        string   `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{16}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Channel) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Channel) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

func (m *Channel) GetLastHeartbeat() string {
	if m != nil {
		return m.LastHeartbeat
	}
	return ""
}

type ListResponse struct {
	Channels             []*Channel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baee4f6301954b8c, []int{17}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

func init() {
	proto.RegisterEnum("sims.proto.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("sims.proto.EventType", EventType_name, EventType_value)
	proto.RegisterType((*ServerConfig)(nil), "sims.proto.ServerConfig")
	proto.RegisterType((*User)(nil), "sims.proto.User")
	proto.RegisterType((*Header)(nil), "sims.proto.Header")
	proto.RegisterType((*Event)(nil), "sims.proto.Event")
	proto.RegisterType((*EventsRequest)(nil), "sims.proto.EventsRequest")
	proto.RegisterType((*ConnectRequest)(nil), "sims.proto.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "sims.proto.ConnectResponse")
	proto.RegisterType((*DisconnectRequest)(nil), "sims.proto.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "sims.proto.DisconnectResponse")
	proto.RegisterType((*PublishRequest)(nil), "sims.proto.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "sims.proto.PublishResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "sims.proto.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "sims.proto.SubscribeResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "sims.proto.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "sims.proto.HeartbeatResponse")
	proto.RegisterType((*ListRequest)(nil), "sims.proto.ListRequest")
	proto.RegisterType((*Channel)(nil), "sims.proto.Channel")
	proto.RegisterType((*ListResponse)(nil), "sims.proto.ListResponse")
}

func init() { proto.RegisterFile("sims.proto", fileDescriptor_baee4f6301954b8c) }

var fileDescriptor_baee4f6301954b8c = []byte{
	// 778 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xa3, 0x46,
	0x14, 0x5e, 0x6c, 0x42, 0xe2, 0x13, 0xc7, 0x3b, 0x9e, 0xec, 0x66, 0x5d, 0xef, 0x8f, 0x22, 0xa4,
	0xaa, 0xdb, 0x5c, 0xc4, 0x95, 0x7b, 0xd3, 0xaa, 0x55, 0x57, 0xfe, 0x19, 0xd7, 0xb4, 0x59, 0xb0,
	0x06, 0x6c, 0x6d, 0xaa, 0x4a, 0x08, 0xcc, 0x34, 0x46, 0xf2, 0x1a, 0x77, 0x06, 0x22, 0xad, 0xd4,
	0xb7, 0xeb, 0x33, 0xf4, 0x7d, 0xaa, 0x01, 0xcc, 0x82, 0xbd, 0xb9, 0xc9, 0x15, 0x9c, 0xef, 0xfc,
	0x7f, 0x73, 0xce, 0x01, 0x10, 0xe1, 0x47, 0x71, 0xbd, 0xe5, 0x51, 0x1c, 0xe1, 0xd2, 0xbf, 0xde,
	0x82, 0xa6, 0xcd, 0xf8, 0x3d, 0xe3, 0xa3, 0x68, 0xf3, 0x57, 0x78, 0xa7, 0x6b, 0xa0, 0xce, 0x05,
	0xe3, 0x7a, 0x02, 0xda, 0x94, 0x79, 0x01, 0xe3, 0xf8, 0x35, 0x00, 0x67, 0x7f, 0x27, 0x4c, 0xc4,
	0x6e, 0x18, 0x74, 0x94, 0x4b, 0xe5, 0x6d, 0x83, 0x36, 0x72, 0xc4, 0x08, 0xf0, 0x0b, 0x38, 0x4e,
	0x04, 0xe3, 0x52, 0x57, 0x4b, 0x75, 0x9a, 0x14, 0x8d, 0x00, 0xbf, 0x84, 0x46, 0xc0, 0xee, 0xc3,
	0x25, 0x93, 0xaa, 0x7a, 0xaa, 0x3a, 0xc9, 0x00, 0x23, 0xc0, 0x17, 0xa0, 0xdd, 0xf1, 0x28, 0xd9,
	0x8a, 0x8e, 0x7a, 0x59, 0x97, 0x4e, 0x99, 0xa4, 0x4f, 0xe0, 0x88, 0xdc, 0xb3, 0x4d, 0x8c, 0xbf,
	0x05, 0x35, 0xfe, 0xb4, 0x65, 0x69, 0xbe, 0x56, 0xff, 0xf9, 0xf5, 0xe7, 0x92, 0xaf, 0x53, 0x03,
	0xe7, 0xd3, 0x96, 0xd1, 0xd4, 0x04, 0x63, 0x50, 0x03, 0x2f, 0xf6, 0xd2, 0xf4, 0x4d, 0x9a, 0xfe,
	0xeb, 0x3f, 0xc1, 0x59, 0x6a, 0x26, 0x68, 0x56, 0x28, 0xbe, 0x02, 0x6d, 0x95, 0xf6, 0x93, 0x46,
	0x3c, 0xed, 0xe3, 0x72, 0xc4, 0xac, 0x53, 0x9a, 0x5b, 0xe8, 0x3f, 0x43, 0x6b, 0x14, 0x6d, 0x36,
	0x6c, 0x19, 0x3f, 0xc6, 0xbb, 0x0d, 0x4f, 0x0b, 0x6f, 0xb1, 0x8d, 0x36, 0x82, 0xe9, 0xef, 0xa0,
	0x3d, 0x0e, 0xc5, 0xf2, 0xf1, 0x31, 0x9f, 0x01, 0x2e, 0x07, 0xc8, 0xc3, 0x52, 0x68, 0xcd, 0x12,
	0x7f, 0x1d, 0x8a, 0xd5, 0x2e, 0x66, 0xe9, 0x31, 0x94, 0xca, 0x63, 0x7c, 0x03, 0x47, 0x4c, 0xf2,
	0x91, 0x92, 0x74, 0xda, 0x6f, 0x1f, 0xf0, 0x49, 0x33, 0xbd, 0xac, 0xbe, 0x88, 0x99, 0xa7, 0xc1,
	0x80, 0xec, 0xc4, 0x17, 0x4b, 0x1e, 0xfa, 0x2c, 0x4f, 0xa4, 0x9f, 0x43, 0xbb, 0x84, 0xe5, 0x86,
	0xbf, 0x00, 0x9a, 0x32, 0x8f, 0xc7, 0x3e, 0xf3, 0x1e, 0xd5, 0xe5, 0x39, 0xb4, 0x4b, 0xfe, 0x79,
	0xd0, 0x33, 0x38, 0xbd, 0x09, 0xc5, 0x2e, 0x9e, 0xfe, 0x0f, 0x1c, 0x8f, 0x56, 0xde, 0x66, 0xc3,
	0xd6, 0x0f, 0x37, 0x5b, 0x99, 0xbc, 0xda, 0xde, 0xe4, 0x3d, 0x83, 0x23, 0x3f, 0xe4, 0xf1, 0x2a,
	0x1f, 0xc9, 0x4c, 0xc0, 0x5f, 0x43, 0x6b, 0xed, 0x89, 0xd8, 0x5d, 0xed, 0xf2, 0x77, 0xd4, 0x54,
	0x7d, 0x26, 0xd1, 0xa2, 0x28, 0xfd, 0x1d, 0x34, 0xb3, 0x62, 0xb2, 0xe2, 0x70, 0x0f, 0x4e, 0x96,
	0x59, 0x35, 0xa2, 0xa3, 0x5c, 0xd6, 0xdf, 0x9e, 0xf6, 0xcf, 0xcb, 0xfd, 0xe5, 0x95, 0xd2, 0xc2,
	0xe8, 0xea, 0x5f, 0x05, 0x1a, 0x84, 0xf3, 0x88, 0x8f, 0xa2, 0x80, 0xe1, 0x73, 0x78, 0x4a, 0x28,
	0x75, 0xe7, 0xa6, 0x3d, 0x23, 0x23, 0x63, 0x62, 0x90, 0x31, 0x7a, 0x82, 0xdb, 0x70, 0x26, 0x41,
	0xd3, 0x72, 0xdc, 0x89, 0x35, 0x37, 0xc7, 0x48, 0xc1, 0x17, 0x80, 0x25, 0x34, 0xb8, 0xa1, 0x64,
	0x30, 0xbe, 0x75, 0xc9, 0x07, 0xc3, 0x76, 0x6c, 0x54, 0xdb, 0xe1, 0xef, 0x0d, 0xdb, 0x36, 0xcc,
	0x5f, 0xdd, 0xb9, 0x4d, 0xa8, 0x31, 0x46, 0xf5, 0x7d, 0x7c, 0x4a, 0x06, 0x63, 0x42, 0x91, 0xba,
	0xcb, 0x67, 0x5a, 0xee, 0xc8, 0x32, 0xed, 0xf9, 0x7b, 0x42, 0xd1, 0x11, 0x7e, 0x0e, 0xed, 0xb2,
	0x31, 0x59, 0x10, 0xd3, 0x41, 0x1a, 0xee, 0xc2, 0x85, 0x84, 0x0d, 0x73, 0x31, 0xb8, 0x31, 0xc6,
	0x19, 0xec, 0x3a, 0xb7, 0x33, 0x82, 0x8e, 0xaf, 0xfe, 0x84, 0x46, 0xb1, 0x84, 0x69, 0xbd, 0x0b,
	0x47, 0x26, 0xa1, 0xce, 0x90, 0x0c, 0x1c, 0xf4, 0x04, 0x37, 0xe1, 0x44, 0x42, 0x0e, 0xf9, 0xe0,
	0x20, 0x65, 0x27, 0xfd, 0x66, 0x5b, 0x26, 0xaa, 0x61, 0x04, 0x4d, 0x29, 0xcd, 0xa8, 0xe5, 0x58,
	0xc3, 0xf9, 0x04, 0xd5, 0x71, 0x0b, 0x40, 0x22, 0x43, 0xc3, 0x1c, 0xd0, 0x5b, 0xa4, 0xf6, 0xff,
	0xab, 0x41, 0x7d, 0x9a, 0xf8, 0x78, 0x08, 0xc7, 0xf9, 0x22, 0xe1, 0x6e, 0x85, 0xd5, 0xca, 0x1e,
	0x75, 0x5f, 0x7e, 0x51, 0x97, 0x3f, 0xd0, 0x14, 0x1a, 0xc5, 0xeb, 0xe1, 0x57, 0x7b, 0xb3, 0x57,
	0x99, 0xd4, 0xee, 0xeb, 0x07, 0xb4, 0x79, 0xa4, 0x1f, 0x40, 0xcb, 0x2e, 0x0a, 0xfe, 0xea, 0x60,
	0x79, 0x76, 0x57, 0xa6, 0x7b, 0xb8, 0x57, 0xdf, 0x29, 0xf8, 0x77, 0x80, 0xcf, 0xcb, 0x8b, 0x2b,
	0x69, 0x0e, 0xae, 0x42, 0xf7, 0xcd, 0x43, 0xea, 0xbc, 0x8c, 0x1f, 0x41, 0x95, 0x13, 0x88, 0x5f,
	0x94, 0xed, 0x4a, 0x0b, 0xd2, 0xed, 0x1c, 0x2a, 0x32, 0xd7, 0xbe, 0x05, 0x8d, 0x7c, 0xb5, 0x19,
	0x97, 0xe4, 0xe6, 0x42, 0x95, 0xdc, 0xea, 0x41, 0xa9, 0x92, 0xbb, 0x77, 0x18, 0xfa, 0x0b, 0x80,
	0xe2, 0x08, 0x70, 0x49, 0x75, 0x21, 0x55, 0xa9, 0xde, 0xbf, 0x1e, 0x55, 0xaa, 0x0f, 0xee, 0xc8,
	0xf0, 0xcd, 0x1f, 0xaf, 0xee, 0xc2, 0x78, 0x95, 0xf8, 0xd7, 0xcb, 0xe8, 0x63, 0xcf, 0x5b, 0xae,
	0x43, 0xb1, 0xed, 0x49, 0x8f, 0x5e, 0xea, 0xe1, 0x6b, 0xe9, 0xe7, 0xfb, 0xff, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0xf3, 0x1a, 0x05, 0xd4, 0x06, 0x00, 0x00,
}
