name: Docker

on:
  push:
    branches:
    - master
    tags:
    - v2.*
    - v3.*
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: elgohr/Publish-Docker-Github-Action@2.12
         name: Build and Push Docker Image
         with:
           name: micro/go-micro
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           tag_names: true