name: Build and test micro
on:
  push: 
    branches:
      - 'release-**'

jobs:

  build:
    name: Build and test micro
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out this code
      uses: actions/checkout@v2
      with:
        path: 'go-micro'

    - name: Check out micro
      uses: actions/checkout@v2
      with:
        repository: 'micro/micro'
        path: 'micro'

    - name: Build all
      run: $GITHUB_WORKSPACE/go-micro/.github/workflows/scripts/build-micro.sh $GITHUB_SHA
      working-directory: micro
    